name: py39Rep2Mut
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.9.13
  - fair-esm=2.0.0
  - torch=1.8.1+cu111
  - pandas=1.4.4
  - scipy=1.9.1
  - matplotlib=3.5.2
  - scikit-learn=1.0.2
  - plotly=5.9.0